### ISSUE TITLE
typo to 'usermod -aG libvirt'

### ISSUE THREAD

**Issue by murasesyuka** [satoru-takeuchi/elkdat#3]
I try install them on Ubuntu 16.04. 
but fail 'usermod'.  as follows

``` shell
$ sudo usermod -aG libvirt murase
usermod: group 'libvirt' does not exist
```

Is thisi a "libvirtd" typo?

``` shell
$ cat /etc/group | grep libvir
libvirtd:x:130:
```

**Comment by satoru-takeuchi** [comment]
Thank you for letting me know. Yes, it's a typo.

I fixed it as the following commit.
https://github.com/satoru-takeuchi/elkdat/commit/ca4ea840f1ecf7c4b449f37bcdd582b156c8e2ef

If I'll confirm this new description works for you, I'll close this ticket.

**Comment by murasesyuka** [comment]
thank you fix :-D
